platform :ios, '10.0'
use_frameworks!

target 'SwiftAudio_Example' do
  pod 'SwiftAudio', :path => '../'

  target 'SwiftAudio_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.0'
    pod 'Nimble' , '~> 7.3.0'
    
  end
end
