platform :ios, '10.0'
use_frameworks!

target 'SwiftAudio_Example' do
  pod 'SwiftAudio', :path => '../'

  target 'SwiftAudio_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    
  end
end
