name: validate
on: [push]
jobs:
  run-tests:
    name: Test
    runs-on: [self-hosted, macOS, arm64e]
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    strategy:
      matrix:
        destination:
          [
            'platform=iOS Simulator,name=iPhone 12 Pro',
          ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: |-
          cd Example
          xcodebuild test -scheme SwiftAudio-Example -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}